import type { Dispatch, MutableRefObject, RefObject, SetStateAction } from "react";
import type { NavigateFunction } from "react-router-dom";
import type { ChatMessage } from "../../application/gateway";
import type { Company } from "../../domain/org/types";
import type { DispatchRecord, RequirementRoomRecord } from "../../domain/delegation/types";
import type { WorkItemRecord } from "../../domain/mission/types";
import type { RequirementSessionSnapshot } from "../../domain/mission/requirement-snapshot";
import type { RequirementExecutionOverview } from "../../application/mission/requirement-overview-types";
import type { RequirementTeamView } from "../../application/assignment/requirement-team";
import type { SummaryPanelView } from "./components/chat-summary-panel-types";
import { useChatPageMissionState } from "./hooks/useChatPageMissionState";
import { useChatPagePresentationState } from "./hooks/useChatPagePresentationState";
import { useChatConversationSurface } from "./hooks/useChatConversationSurface";
import { useChatSessionContext } from "./hooks/useChatSessionContext";
import { useChatSessionHistory } from "./hooks/useChatSessionHistory";
import { useChatUploads } from "./hooks/useChatUploads";
import { useChatDragAndDrop } from "./hooks/useChatDragAndDrop";
import { useChatWorkspaceViewModel } from "./hooks/useChatWorkspaceViewModel";
import { useChatRouteCompanyState } from "./hooks/useChatRouteCompanyState";
import { useChatSignalState } from "./hooks/useChatSignalState";
import { useChatPanelState } from "./hooks/useChatPanelState";
import { useChatCompanySnapshots } from "./hooks/useChatCompanySnapshots";
import type { LiveChatSessionState } from "../../application/chat/live-session-cache";

type WorkspaceViewModel = ReturnType<typeof useChatWorkspaceViewModel>;
type RouteCompanyState = ReturnType<typeof useChatRouteCompanyState>;
type SessionContextState = ReturnType<typeof useChatSessionContext>;
type ConversationSurfaceState = ReturnType<typeof useChatConversationSurface>;
type SessionHistoryState = ReturnType<typeof useChatSessionHistory>;
type UploadState = ReturnType<typeof useChatUploads>;
type DragAndDropState = ReturnType<typeof useChatDragAndDrop>;
type SignalState = ReturnType<typeof useChatSignalState>;
type PanelState = ReturnType<typeof useChatPanelState>;
type CompanySnapshotsState = ReturnType<typeof useChatCompanySnapshots>;

export type ChatPageBodyBase = {
  loading: boolean;
  agentId: string | null;
  emp: SessionContextState["targetEmployee"];
  activeCompany: Company | null;
  activeDispatches: DispatchRecord[];
  activeRoomRecords: RequirementRoomRecord[];
  activeArtifacts: ChatMessage[];
  activeArchivedRound: SessionContextState["activeArchivedRound"];
  archiveId: string | null;
  attachments: { mimeType: string; dataUrl: string }[];
  authorityBackedState: boolean;
  ceoSurface: SessionContextState["ceoSurface"];
  composerPrefill: { id: string | number; text: string } | null;
  connected: boolean;
  conversationStateKey: string | null;
  currentConversationRequirementHint: ConversationSurfaceState["currentConversationRequirementHint"];
  decisionSubmittingOptionId: string | null;
  effectiveRequirementRoom: ConversationSurfaceState["effectiveRequirementRoom"];
  endRef: RefObject<HTMLDivElement | null>;
  expandDisplayWindow: () => void;
  fileInputRef: RefObject<HTMLInputElement | null>;
  forceScrollOnNextUpdateRef: MutableRefObject<boolean>;
  groupTopic: string | null;
  groupWorkItemId: string | null;
  handleDragLeave: DragAndDropState["handleDragLeave"];
  handleDragOver: DragAndDropState["handleDragOver"];
  handleDrop: DragAndDropState["handleDrop"];
  handleFileSelect: UploadState["handleFileSelect"];
  handoffPreview: SessionContextState["handoffPreview"];
  historyLoading: boolean;
  historyRoundItems: SessionContextState["historyRoundItems"];
  historySessionPresentations: SessionContextState["historySessionPresentations"];
  isArchiveView: boolean;
  isCeoSession: boolean;
  isDragging: boolean;
  isFreshConversation: boolean;
  isGenerating: boolean;
  isGroup: boolean;
  isHistoryMenuOpen: boolean;
  isNearBottom: (element: HTMLElement | null) => boolean;
  isRequirementBootstrapPending: boolean;
  isSummaryOpen: boolean;
  isTechnicalSummaryOpen: boolean;
  lastScrollTopRef: MutableRefObject<number>;
  latestDirectTurnSummary: ConversationSurfaceState["latestDirectTurnSummary"];
  localSlaFallbackAlerts: SessionContextState["localSlaFallbackAlerts"];
  lockedScrollTopRef: MutableRefObject<number | null>;
  navigate: NavigateFunction;
  openSummaryPanel: (view?: SummaryPanelView) => void;
  orgAdvisor: SessionContextState["orgAdvisor"];
  persistedWorkItem: ConversationSurfaceState["persistedWorkItem"];
  processImageFile: UploadState["processImageFile"];
  productRoomId: string | null;
  programmaticScrollRef: MutableRefObject<boolean>;
  providerManifest: unknown;
  recentAgentSessions: SessionHistoryState["recentAgentSessions"];
  recoveringCommunication: boolean;
  relatedSlaAlerts: SessionContextState["relatedSlaAlerts"];
  requestHealth: SessionContextState["requestHealth"];
  requestPreview: SessionContextState["requestPreview"];
  requirementCollaborationSurface: ReturnType<typeof useChatPageMissionState>["requirementCollaborationSurface"];
  requirementOverview: ConversationSurfaceState["requirementOverview"];
  requirementRoomMentionCandidates: SessionContextState["requirementRoomMentionCandidates"];
  requirementRoomSessions: SessionContextState["requirementRoomSessions"];
  requirementTeam: ConversationSurfaceState["requirementTeam"];
  roomBroadcastMode: string;
  routeCompanyConflictMessage: string | null;
  routeComposerPrefill: string | null;
  runningFocusActionId: string | null;
  scrollContainerRef: MutableRefObject<HTMLElement | null>;
  sending: boolean;
  sessionExecution: SessionContextState["sessionExecution"];
  sessionKey: string | null;
  setAttachments: Dispatch<SetStateAction<{ mimeType: string; dataUrl: string }[]>>;
  setConversationCurrentWorkKey?: (conversationId: string, workKey: string | null) => void;
  setIsHistoryMenuOpen: Dispatch<SetStateAction<boolean>>;
  setIsSummaryOpen: Dispatch<SetStateAction<boolean>>;
  setIsTechnicalSummaryOpen: Dispatch<SetStateAction<boolean>>;
  setRoomBroadcastMode: Dispatch<SetStateAction<string>>;
  setSummaryPanelView: Dispatch<SetStateAction<SummaryPanelView>>;
  setThinkingLevel: Dispatch<SetStateAction<string>>;
  shouldAutoScrollRef: MutableRefObject<boolean>;
  structuredTaskPreview: SessionContextState["structuredTaskPreview"];
  summaryAlertCount: number;
  summaryPanelView: SummaryPanelView;
  supportsSessionArchiveRestore: boolean;
  supportsSessionHistory: boolean;
  syncAutoScrollPosition: () => void;
  takeoverPack: SessionContextState["takeoverPack"];
  targetAgentId: string | null;
  thinkingLevel: string;
  uploadingFile: boolean;
  upsertDispatchRecord: (...args: unknown[]) => unknown;
  upsertWorkItemRecord: (...args: unknown[]) => unknown;
  userScrollLockRef: MutableRefObject<boolean>;
};

export type ChatPageBodyProps = {
  base: ChatPageBodyBase;
  missionState: ReturnType<typeof useChatPageMissionState>;
  presentationState: ReturnType<typeof useChatPagePresentationState>;
};

export type ChatPageMissionStateInput = {
  [key: string]: unknown;
  actionWatches: SignalState["actionWatches"];
  activeArtifacts: WorkspaceViewModel["activeArtifacts"];
  activeCompany: WorkspaceViewModel["activeCompany"];
  activeConversationState: RouteCompanyState["activeConversationState"];
  activeConversationStates: WorkspaceViewModel["activeConversationStates"];
  activeDecisionTickets: WorkspaceViewModel["activeDecisionTickets"];
  activeDispatches: WorkspaceViewModel["activeDispatches"];
  activeMissionRecords: WorkspaceViewModel["activeMissionRecords"];
  activeRequirementAggregates: WorkspaceViewModel["activeRequirementAggregates"];
  activeRequirementEvidence: WorkspaceViewModel["activeRequirementEvidence"];
  activeRoomRecords: WorkspaceViewModel["activeRoomRecords"];
  activeWorkItems: WorkspaceViewModel["activeWorkItems"];
  appendLocalProgressEvent: SignalState["appendLocalProgressEvent"];
  authorityBackedState: WorkspaceViewModel["authorityBackedState"];
  ceoReplyExplicitlyRequestsNewTask: ConversationSurfaceState["ceoReplyExplicitlyRequestsNewTask"];
  ceoSurface: SessionContextState["ceoSurface"];
  companySessionSnapshots: RequirementSessionSnapshot[];
  companySessionSnapshotsRef: MutableRefObject<RequirementSessionSnapshot[]>;
  conversationStateKey: string | null;
  currentTime: number;
  effectiveRequirementRoom: ConversationSurfaceState["effectiveRequirementRoom"];
  effectiveRequirementRoomSnapshots: ConversationSurfaceState["effectiveRequirementRoomSnapshots"];
  emp: SessionContextState["targetEmployee"];
  ensureRequirementRoomForAggregate: WorkspaceViewModel["ensureRequirementRoomForAggregate"];
  groupTitle: RouteCompanyState["groupTitle"];
  groupTopic: RouteCompanyState["groupTopic"];
  groupTopicKey: RouteCompanyState["groupTopicKey"];
  groupWorkItemId: RouteCompanyState["groupWorkItemId"];
  handoffPreview: SessionContextState["handoffPreview"];
  hasStableConversationWorkItem: ConversationSurfaceState["hasStableConversationWorkItem"];
  historyAgentId: RouteCompanyState["historyAgentId"];
  isArchiveView: RouteCompanyState["isArchiveView"];
  isCeoSession: SessionContextState["isCeoSession"];
  isFreshConversation: SessionContextState["isFreshConversation"];
  isGroup: RouteCompanyState["isGroup"];
  isRequirementBootstrapPending: SessionContextState["isRequirementBootstrapPending"];
  isSummaryOpen: boolean;
  lastSyncedRoomSignatureRef: MutableRefObject<string | null>;
  latestMessageTimestamp: SessionContextState["latestMessageTimestamp"];
  linkedRequirementRoom: ConversationSurfaceState["linkedRequirementRoom"];
  localProgressEvents: SignalState["localProgressEvents"];
  localSlaFallbackAlerts: SessionContextState["localSlaFallbackAlerts"];
  messages: RouteCompanyState["messages"];
  navigate: NavigateFunction;
  nextOpenTaskStepAgentId: SessionContextState["nextOpenTaskStepAgentId"];
  nextOpenTaskStepLabel: SessionContextState["nextOpenTaskStepLabel"];
  openSummaryPanel: PanelState["openSummaryPanel"];
  persistedWorkItem: ConversationSurfaceState["persistedWorkItem"];
  preferredConversationTopicKey: ConversationSurfaceState["preferredConversationTopicKey"];
  preferredConversationWorkKey: ConversationSurfaceState["preferredConversationWorkKey"];
  previewConversationWorkItem: ConversationSurfaceState["previewConversationWorkItem"];
  previewTimestamp: SessionContextState["previewTimestamp"];
  primaryRequirementId: WorkspaceViewModel["primaryRequirementId"];
  productRoomId: RouteCompanyState["productRoomId"];
  publishDispatchTargetAgentId: string | null;
  publishDispatchTargetLabel: string | null;
  relatedSlaAlerts: SessionContextState["relatedSlaAlerts"];
  replaceDispatchRecords: WorkspaceViewModel["replaceDispatchRecords"];
  requestPreview: SessionContextState["requestPreview"];
  requirementOverview: ConversationSurfaceState["requirementOverview"];
  requirementProgressGroups: ConversationSurfaceState["requirementProgressGroups"];
  requirementRoomSessions: SessionContextState["requirementRoomSessions"];
  requirementRoomTargetAgentIds: SessionContextState["requirementRoomTargetAgentIds"];
  requirementTeam: ConversationSurfaceState["requirementTeam"];
  roomBoundWorkItem: ConversationSurfaceState["roomBoundWorkItem"];
  routeCompanyConflictMessage: RouteCompanyState["routeCompanyConflictMessage"];
  sessionExecution: SessionContextState["sessionExecution"];
  sessionKey: string | null;
  sessionProgressEvents: SessionContextState["sessionExecution"]["events"] | undefined;
  setCompanySessionSnapshots: CompanySnapshotsState["setCompanySessionSnapshots"];
  setConversationCurrentWorkKey: WorkspaceViewModel["setConversationCurrentWorkKey"];
  setConversationDraftRequirement: WorkspaceViewModel["setConversationDraftRequirement"];
  shouldPreferPreviewConversationWorkItem: ConversationSurfaceState["shouldPreferPreviewConversationWorkItem"];
  shouldUsePersistedWorkItemPrimaryView: ConversationSurfaceState["shouldUsePersistedWorkItemPrimaryView"];
  stableDisplayPrimaryView: ConversationSurfaceState["stableDisplayPrimaryView"];
  stableDisplayWorkItem: ConversationSurfaceState["stableDisplayWorkItem"];
  structuredTaskPreview: SessionContextState["structuredTaskPreview"];
  summaryAlertCount: SessionContextState["summaryAlertCount"];
  summaryPanelView: PanelState["summaryPanelView"];
  takeoverPack: SessionContextState["takeoverPack"];
  targetAgentId: RouteCompanyState["targetAgentId"];
  taskPlanOverview: ConversationSurfaceState["taskPlanOverview"];
  updateCompany: WorkspaceViewModel["updateCompany"];
  upsertMissionRecord: WorkspaceViewModel["upsertMissionRecord"];
  upsertRoomRecord: WorkspaceViewModel["upsertRoomRecord"];
  upsertWorkItemRecord: WorkspaceViewModel["upsertWorkItemRecord"];
};

export type ChatPagePresentationStateInput = {
  [key: string]: unknown;
  actionWatches: SignalState["actionWatches"];
  activeArchivedRound: SessionContextState["activeArchivedRound"];
  activeCompany: WorkspaceViewModel["activeCompany"];
  activeDispatches: WorkspaceViewModel["activeDispatches"];
  activeRequirementEvidence: WorkspaceViewModel["activeRequirementEvidence"];
  activeRoomBindings: WorkspaceViewModel["activeRoomBindings"];
  activeRoomRecords: WorkspaceViewModel["activeRoomRecords"];
  activeRunIdRef: MutableRefObject<string | null>;
  agentId: RouteCompanyState["agentId"];
  appendLocalProgressEvent: SignalState["appendLocalProgressEvent"];
  appendRoomMessages: WorkspaceViewModel["appendRoomMessages"];
  archiveHistoryNotice: SessionHistoryState["archiveHistoryNotice"];
  archiveId: RouteCompanyState["archiveId"];
  attachments: { mimeType: string; dataUrl: string }[];
  authorityBackedState: WorkspaceViewModel["authorityBackedState"];
  autoScrollFrameRef: MutableRefObject<number | null>;
  beginGeneratingState: (
    startedAt: number,
    options?: { runId?: string | null; streamText?: string | null; persist?: boolean },
  ) => void;
  clearConversationState: WorkspaceViewModel["clearConversationState"];
  clearGeneratingState: (options?: { preserveRuntime?: boolean }) => void;
  companyRouteReady: RouteCompanyState["companyRouteReady"];
  companySessionSnapshots: RequirementSessionSnapshot[];
  companySessionSnapshotsRef: MutableRefObject<RequirementSessionSnapshot[]>;
  companySyncError: CompanySnapshotsState["companySyncError"];
  companySyncStale: CompanySnapshotsState["companySyncStale"];
  connected: boolean;
  conversationStateKey: string | null;
  currentTime: number;
  deleteRoundRecord: WorkspaceViewModel["deleteRoundRecord"];
  displayWindowSize: number;
  effectiveGroupSessionKey: RouteCompanyState["effectiveGroupSessionKey"];
  effectiveRequirementRoom: ConversationSurfaceState["effectiveRequirementRoom"];
  effectiveRequirementRoomSnapshots: ConversationSurfaceState["effectiveRequirementRoomSnapshots"];
  emp: SessionContextState["targetEmployee"];
  ensureRequirementRoomForAggregate: WorkspaceViewModel["ensureRequirementRoomForAggregate"];
  forceScrollOnNextUpdateRef: MutableRefObject<boolean>;
  groupTitle: RouteCompanyState["groupTitle"];
  groupTopic: RouteCompanyState["groupTopic"];
  groupTopicKey: RouteCompanyState["groupTopicKey"];
  groupWorkItemId: RouteCompanyState["groupWorkItemId"];
  handoffPreview: SessionContextState["handoffPreview"];
  historyAgentId: RouteCompanyState["historyAgentId"];
  historyRoundItems: SessionContextState["historyRoundItems"];
  incrementHistoryRefreshNonce: SessionHistoryState["incrementHistoryRefreshNonce"];
  isArchiveView: RouteCompanyState["isArchiveView"];
  isCeoSession: SessionContextState["isCeoSession"];
  isGenerating: boolean;
  isGroup: RouteCompanyState["isGroup"];
  isPageVisible: boolean;
  isSummaryOpen: boolean;
  lastEnsuredRequirementRoomRef: MutableRefObject<string | null>;
  lastScrollTopRef: MutableRefObject<number>;
  lastSyncedRoomSignatureRef: MutableRefObject<string | null>;
  lastTrackedAutoPromotionRef: MutableRefObject<string | null>;
  lastTrackedDraftKeyRef: MutableRefObject<string | null>;
  lastTrackedStaleRef: MutableRefObject<string | null>;
  latestMessageTimestamp: SessionContextState["latestMessageTimestamp"];
  location: { pathname: string; search: string };
  lockedScrollTopRef: MutableRefObject<number | null>;
  markScrollIntent: (mode?: "preserve" | "follow") => void;
  messages: RouteCompanyState["messages"];
  missionState: ReturnType<typeof useChatPageMissionState>;
  navigate: NavigateFunction;
  pendingGenerationStartedAtRef: MutableRefObject<number | null>;
  persistedWorkItem: ConversationSurfaceState["persistedWorkItem"];
  previewTimestamp: SessionContextState["previewTimestamp"];
  productArchivedRounds: SessionContextState["productArchivedRounds"];
  productRoomId: RouteCompanyState["productRoomId"];
  programmaticScrollRef: MutableRefObject<boolean>;
  providerId: string;
  providerManifest: unknown;
  recentAgentSessions: SessionHistoryState["recentAgentSessions"];
  requestPreview: SessionContextState["requestPreview"];
  requirementOverview: ConversationSurfaceState["requirementOverview"];
  requirementRoomSessionKeys: SessionContextState["requirementRoomSessionKeys"];
  requirementRoomSessions: SessionContextState["requirementRoomSessions"];
  requirementRoomTargetAgentIds: SessionContextState["requirementRoomTargetAgentIds"];
  requirementTeam: ConversationSurfaceState["requirementTeam"];
  resolveDecisionTicket: WorkspaceViewModel["resolveDecisionTicket"];
  restoreGeneratingState: (
    liveSession: Pick<LiveChatSessionState, "runId" | "streamText" | "isGenerating" | "startedAt"> | null,
  ) => void;
  roomBoundWorkItem: ConversationSurfaceState["roomBoundWorkItem"];
  roomBroadcastMode: string;
  routeCompanyConflictMessage: RouteCompanyState["routeCompanyConflictMessage"];
  runningFocusActionId: string | null;
  sending: boolean;
  sessionExecution: SessionContextState["sessionExecution"];
  sessionKey: string | null;
  sessionSyncError: string | null;
  sessionSyncStale: boolean;
  setActionWatches: SignalState["setActionWatches"];
  setActiveRunId: Dispatch<SetStateAction<string | null>>;
  setAttachments: Dispatch<SetStateAction<{ mimeType: string; dataUrl: string }[]>>;
  setCompanySyncStale: CompanySnapshotsState["setCompanySyncStale"];
  setDecisionSubmittingOptionId: Dispatch<SetStateAction<string | null>>;
  setHasBootstrappedCompanySync: CompanySnapshotsState["setHasBootstrappedCompanySync"];
  setIsGenerating: Dispatch<SetStateAction<boolean>>;
  setIsSummaryOpen: PanelState["setIsSummaryOpen"];
  setIsTechnicalSummaryOpen: PanelState["setIsTechnicalSummaryOpen"];
  setLoading: Dispatch<SetStateAction<boolean>>;
  setLocalProgressEvents: SignalState["setLocalProgressEvents"];
  setMessages: Dispatch<SetStateAction<ChatMessage[]>>;
  setRecentAgentSessions: SessionHistoryState["setRecentAgentSessions"];
  setRecentArchivedRounds: SessionHistoryState["setRecentArchivedRounds"];
  setRecoveringCommunication: Dispatch<SetStateAction<boolean>>;
  setRoomBroadcastMode: Dispatch<SetStateAction<string>>;
  setRunningFocusActionId: Dispatch<SetStateAction<string | null>>;
  setSending: Dispatch<SetStateAction<boolean>>;
  setSessionKey: Dispatch<SetStateAction<string | null>>;
  setSessionSyncError: Dispatch<SetStateAction<string | null>>;
  setSessionSyncStale: Dispatch<SetStateAction<boolean>>;
  shouldAutoScrollRef: MutableRefObject<boolean>;
  streamTextRef: MutableRefObject<string | null>;
  structuredTaskPreview: SessionContextState["structuredTaskPreview"];
  supportsSessionArchiveRestore: boolean;
  syncAutoScrollPosition: () => void;
  takeoverPack: SessionContextState["takeoverPack"];
  targetAgentId: RouteCompanyState["targetAgentId"];
  thinkingLevel: string;
  upsertDispatchRecord: WorkspaceViewModel["upsertDispatchRecord"];
  upsertHandoff: WorkspaceViewModel["upsertHandoff"];
  upsertRequest: WorkspaceViewModel["upsertRequest"];
  upsertRoomConversationBindings: WorkspaceViewModel["upsertRoomConversationBindings"];
  upsertRoomRecord: WorkspaceViewModel["upsertRoomRecord"];
  upsertRoundRecord: WorkspaceViewModel["upsertRoundRecord"];
  upsertTask: WorkspaceViewModel["upsertTask"];
  updateCompany: WorkspaceViewModel["updateCompany"];
  updateStreamText: (value: string | null) => void;
  userScrollLockRef: MutableRefObject<boolean>;
};
